
spring:
    application:
        name: products-api
    datasource:
        url: jdbc:postgresql://localhost:5433/products
        username: admin
        password: secret
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate.ddl-auto: validate
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        liquibase:
            change-log: classpath:db/changelog/db.changelog-master.yml
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
    security:
      user:
        name: admin
        password: admin

server:
    port: 8082

